[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ru-wifi"
dynamic = ["version"]
description = 'RU-WiFi auto login'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "copilot-swe-agent[bot]", email = "198982749+Copilot@users.noreply.github.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "click",
]

[project.urls]
Documentation = "https://github.com/copilot-swe-agent[bot]/ru-wifi#readme"
Issues = "https://github.com/copilot-swe-agent[bot]/ru-wifi/issues"
Source = "https://github.com/copilot-swe-agent[bot]/ru-wifi"

[project.scripts]
ru-wifi = "ru_wifi.cli:ru_wifi"

[tool.hatch.version]
path = "src/ru_wifi/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/ru_wifi tests}"

[tool.coverage.run]
source_pkgs = ["ru_wifi", "tests"]
branch = true
parallel = true
omit = [
  "src/ru_wifi/__about__.py",
]

[tool.coverage.paths]
ru_wifi = ["src/ru_wifi", "*/ru-wifi/src/ru_wifi"]
tests = ["tests", "*/ru-wifi/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
