#!/bin/sh
# Trigger login when NetworkManager reports a connection change.

INTERFACE="$1"
STATUS="$2"

case "$STATUS" in
    up|dhcp4-change|dhcp6-change|connectivity-change)
        /usr/bin/ru-wifi login
        ;;
esac
